Added commented out board.STEMMA_I2C with explanation
adafruit/Adafruit_CircuitPython_MLX90640 pull request #32
Opened 2022-11-18 20:45 UTC by evaherrada

2022-11-22 19:43 UTC, evaherrada commented
need to re-do

2022-12-07 02:15 UTC, tekktrik approved these changes

2022-12-07 02:20 UTC, tekktrik requested changes
Sorry, missed your follow up comment, should I set this to draft?

2024-06-10 21:54 UTC, FoamyGuy approved these changes
I think this is ready to merge. 

I added a commit that added the comented stemma I2C line in the two MCU examples, and removed it from the PIL example because that is for Raspberry Pi only and I don't think any of them will have `board.STEMMA_I2C` we can add it back later though if there are some that have it.

2024-06-10 21:55 UTC, merged